### ISSUE TITLE
Remove organisation endpoint :)

### ISSUE THREAD

**Issue by mattwoberts** [dawitnida/timetastic-postman#1]
Hi there!

I work at Timeastic, just came along to say nice work with this - I'm checking it out right now, but it all looks good!

Quick thing - We're removing the "Organisation" API endpoint - that you correctly point out is broken, so any references to that need to come out :)

**Comment by dchonch** [comment]
Hi,

Thanks for the feedback. I've removed the endpoint and also it's traces.
